### PR TITLE
Fix Tooltips requiring UnityEditor

### LINKED ISSUE #258: Unable to build
Unable to build in VR4VET repo due to PrefabUtility in TooltipManager.cs that uses UnityEditor.

### PR DESCRIPTION
**Pull request by SnorreForbregd**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Tooltips requires a UnityEditor extension, which means it can't be built into an app. The extension used is the PrefabUtility to instantiate prefabs.

* **What is the new behavior?** (if this is a feature change)
Now uses Instantiate instead of InstantiatePrefab, removing the need for UnityEditor.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
Fixes #258

### CODE REVIEW

**Review by qlpham231 — CHANGES_REQUESTED** [review]
It's still not possible to build. This needs to be fixed: 
image
Remember to try building. In project settings, xr plug-in management we're seeing a red exclamation mark beside open-xr

**Comment by SnorreForbregd** [comment]
I managed to build successfully, you just need to press the "fix" button in the screenshot you sent

**Comment by qlpham231** [comment]
I know but I opted to let you commit it since it's your branch. I think you should commit it so others doesn't have to do it

**Comment by SnorreForbregd** [comment]
I believe that file is part of the gitignore, and can't be pushed

**Review by qlpham231 — APPROVED** [review]
I should have fixed it now, check if it works now.

**Review by eamathie — APPROVED** [review]
Builds and runs on the Quest 2

**Pull request merged**
